// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/passport.proto

/*
	Package api is a generated protocol buffer package.

	It is generated from these files:
		api/passport.proto

	It has these top-level messages:
		SessionTokenReq
		PassportUserReply
		RegisterReq
		LoginReq
		ChangePasswordReq
		IndentifyReply
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import api1 "knowledgemap_backend/microservices/knowledgemap/user/api"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Indentify int32

const (
	Indentify_STUDENT   Indentify = 0
	Indentify_TEACHER   Indentify = 1
	Indentify_SECRETARY Indentify = 2
	Indentify_NOTFOUND  Indentify = -1
)

var Indentify_name = map[int32]string{
	0:  "STUDENT",
	1:  "TEACHER",
	2:  "SECRETARY",
	-1: "NOTFOUND",
}
var Indentify_value = map[string]int32{
	"STUDENT":   0,
	"TEACHER":   1,
	"SECRETARY": 2,
	"NOTFOUND":  -1,
}

func (x Indentify) String() string {
	return proto.EnumName(Indentify_name, int32(x))
}
func (Indentify) EnumDescriptor() ([]byte, []int) { return fileDescriptorPassport, []int{0} }

type RegisterReq_RegisterType int32

const (
	RegisterReq_STUDENT   RegisterReq_RegisterType = 0
	RegisterReq_TEACHER   RegisterReq_RegisterType = 1
	RegisterReq_SECRETARY RegisterReq_RegisterType = 2
)

var RegisterReq_RegisterType_name = map[int32]string{
	0: "STUDENT",
	1: "TEACHER",
	2: "SECRETARY",
}
var RegisterReq_RegisterType_value = map[string]int32{
	"STUDENT":   0,
	"TEACHER":   1,
	"SECRETARY": 2,
}

func (x RegisterReq_RegisterType) String() string {
	return proto.EnumName(RegisterReq_RegisterType_name, int32(x))
}
func (RegisterReq_RegisterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorPassport, []int{2, 0}
}

type LoginReq_LoginType int32

const (
	LoginReq_STUDENT   LoginReq_LoginType = 0
	LoginReq_TEACHER   LoginReq_LoginType = 1
	LoginReq_SECRETARY LoginReq_LoginType = 2
	LoginReq_NOTFOUND  LoginReq_LoginType = -1
)

var LoginReq_LoginType_name = map[int32]string{
	0:  "STUDENT",
	1:  "TEACHER",
	2:  "SECRETARY",
	-1: "NOTFOUND",
}
var LoginReq_LoginType_value = map[string]int32{
	"STUDENT":   0,
	"TEACHER":   1,
	"SECRETARY": 2,
	"NOTFOUND":  -1,
}

func (x LoginReq_LoginType) String() string {
	return proto.EnumName(LoginReq_LoginType_name, int32(x))
}
func (LoginReq_LoginType) EnumDescriptor() ([]byte, []int) { return fileDescriptorPassport, []int{3, 0} }

type SessionTokenReq struct {
	Uid    string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Stoken string `protobuf:"bytes,2,opt,name=stoken,proto3" json:"stoken,omitempty"`
}

func (m *SessionTokenReq) Reset()                    { *m = SessionTokenReq{} }
func (m *SessionTokenReq) String() string            { return proto.CompactTextString(m) }
func (*SessionTokenReq) ProtoMessage()               {}
func (*SessionTokenReq) Descriptor() ([]byte, []int) { return fileDescriptorPassport, []int{0} }

func (m *SessionTokenReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SessionTokenReq) GetStoken() string {
	if m != nil {
		return m.Stoken
	}
	return ""
}

type PassportUserReply struct {
	User    *api1.UserReply `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Token   string          `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expires int64           `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
}

func (m *PassportUserReply) Reset()                    { *m = PassportUserReply{} }
func (m *PassportUserReply) String() string            { return proto.CompactTextString(m) }
func (*PassportUserReply) ProtoMessage()               {}
func (*PassportUserReply) Descriptor() ([]byte, []int) { return fileDescriptorPassport, []int{1} }

func (m *PassportUserReply) GetUser() *api1.UserReply {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PassportUserReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PassportUserReply) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

type RegisterReq struct {
	Rtype        RegisterReq_RegisterType `protobuf:"varint,1,opt,name=rtype,proto3,enum=api.RegisterReq_RegisterType" json:"rtype,omitempty" form:"rtype"`
	Name         string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" form:"name"`
	Major        string                   `protobuf:"bytes,3,opt,name=major,proto3" json:"major,omitempty" form:"major"`
	Idcard       string                   `protobuf:"bytes,4,opt,name=idcard,proto3" json:"idcard,omitempty" form:"idcard"`
	Origin       string                   `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty" form:"origin"`
	Class        string                   `protobuf:"bytes,6,opt,name=class,proto3" json:"class,omitempty" form:"class"`
	Admissontime string                   `protobuf:"bytes,7,opt,name=admissontime,proto3" json:"admissontime,omitempty" form:"admissontime"`
	Account      string                   `protobuf:"bytes,8,opt,name=account,proto3" json:"account,omitempty" form:"account"`
	Password     string                   `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty" form:"password"`
	College      string                   `protobuf:"bytes,10,opt,name=college,proto3" json:"college,omitempty" form:"college"`
	Course       string                   `protobuf:"bytes,11,opt,name=course,proto3" json:"course,omitempty" form:"course"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptorPassport, []int{2} }

func (m *RegisterReq) GetRtype() RegisterReq_RegisterType {
	if m != nil {
		return m.Rtype
	}
	return RegisterReq_STUDENT
}

func (m *RegisterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterReq) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *RegisterReq) GetIdcard() string {
	if m != nil {
		return m.Idcard
	}
	return ""
}

func (m *RegisterReq) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *RegisterReq) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *RegisterReq) GetAdmissontime() string {
	if m != nil {
		return m.Admissontime
	}
	return ""
}

func (m *RegisterReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetCollege() string {
	if m != nil {
		return m.College
	}
	return ""
}

func (m *RegisterReq) GetCourse() string {
	if m != nil {
		return m.Course
	}
	return ""
}

type LoginReq struct {
	Ltype    LoginReq_LoginType `protobuf:"varint,1,opt,name=ltype,proto3,enum=api.LoginReq_LoginType" json:"ltype,omitempty" form:"ltype"`
	Account  string             `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty" form:"account"`
	Password string             `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty" form:"password"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptorPassport, []int{3} }

func (m *LoginReq) GetLtype() LoginReq_LoginType {
	if m != nil {
		return m.Ltype
	}
	return LoginReq_STUDENT
}

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ChangePasswordReq struct {
	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty" form:"account"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" form:"password"`
}

func (m *ChangePasswordReq) Reset()                    { *m = ChangePasswordReq{} }
func (m *ChangePasswordReq) String() string            { return proto.CompactTextString(m) }
func (*ChangePasswordReq) ProtoMessage()               {}
func (*ChangePasswordReq) Descriptor() ([]byte, []int) { return fileDescriptorPassport, []int{4} }

func (m *ChangePasswordReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ChangePasswordReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type IndentifyReply struct {
	Ltype Indentify `protobuf:"varint,1,opt,name=ltype,proto3,enum=api.Indentify" json:"ltype,omitempty" form:"ltype"`
}

func (m *IndentifyReply) Reset()                    { *m = IndentifyReply{} }
func (m *IndentifyReply) String() string            { return proto.CompactTextString(m) }
func (*IndentifyReply) ProtoMessage()               {}
func (*IndentifyReply) Descriptor() ([]byte, []int) { return fileDescriptorPassport, []int{5} }

func (m *IndentifyReply) GetLtype() Indentify {
	if m != nil {
		return m.Ltype
	}
	return Indentify_STUDENT
}

func init() {
	proto.RegisterType((*SessionTokenReq)(nil), "api.SessionTokenReq")
	proto.RegisterType((*PassportUserReply)(nil), "api.PassportUserReply")
	proto.RegisterType((*RegisterReq)(nil), "api.RegisterReq")
	proto.RegisterType((*LoginReq)(nil), "api.LoginReq")
	proto.RegisterType((*ChangePasswordReq)(nil), "api.ChangePasswordReq")
	proto.RegisterType((*IndentifyReply)(nil), "api.IndentifyReply")
	proto.RegisterEnum("api.Indentify", Indentify_name, Indentify_value)
	proto.RegisterEnum("api.RegisterReq_RegisterType", RegisterReq_RegisterType_name, RegisterReq_RegisterType_value)
	proto.RegisterEnum("api.LoginReq_LoginType", LoginReq_LoginType_name, LoginReq_LoginType_value)
}
func (m *SessionTokenReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SessionTokenReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Uid)))
		i += copy(dAtA[i:], m.Uid)
	}
	if len(m.Stoken) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Stoken)))
		i += copy(dAtA[i:], m.Stoken)
	}
	return i, nil
}

func (m *PassportUserReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PassportUserReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.User != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPassport(dAtA, i, uint64(m.User.Size()))
		n1, err := m.User.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Token) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Token)))
		i += copy(dAtA[i:], m.Token)
	}
	if m.Expires != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintPassport(dAtA, i, uint64(m.Expires))
	}
	return i, nil
}

func (m *RegisterReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Rtype != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPassport(dAtA, i, uint64(m.Rtype))
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Major) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Major)))
		i += copy(dAtA[i:], m.Major)
	}
	if len(m.Idcard) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Idcard)))
		i += copy(dAtA[i:], m.Idcard)
	}
	if len(m.Origin) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Origin)))
		i += copy(dAtA[i:], m.Origin)
	}
	if len(m.Class) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Class)))
		i += copy(dAtA[i:], m.Class)
	}
	if len(m.Admissontime) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Admissontime)))
		i += copy(dAtA[i:], m.Admissontime)
	}
	if len(m.Account) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Account)))
		i += copy(dAtA[i:], m.Account)
	}
	if len(m.Password) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Password)))
		i += copy(dAtA[i:], m.Password)
	}
	if len(m.College) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.College)))
		i += copy(dAtA[i:], m.College)
	}
	if len(m.Course) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Course)))
		i += copy(dAtA[i:], m.Course)
	}
	return i, nil
}

func (m *LoginReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Ltype != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPassport(dAtA, i, uint64(m.Ltype))
	}
	if len(m.Account) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Account)))
		i += copy(dAtA[i:], m.Account)
	}
	if len(m.Password) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Password)))
		i += copy(dAtA[i:], m.Password)
	}
	return i, nil
}

func (m *ChangePasswordReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChangePasswordReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Account)))
		i += copy(dAtA[i:], m.Account)
	}
	if len(m.Password) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPassport(dAtA, i, uint64(len(m.Password)))
		i += copy(dAtA[i:], m.Password)
	}
	return i, nil
}

func (m *IndentifyReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndentifyReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Ltype != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPassport(dAtA, i, uint64(m.Ltype))
	}
	return i, nil
}

func encodeVarintPassport(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *SessionTokenReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Stoken)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	return n
}

func (m *PassportUserReply) Size() (n int) {
	var l int
	_ = l
	if m.User != nil {
		l = m.User.Size()
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	if m.Expires != 0 {
		n += 1 + sovPassport(uint64(m.Expires))
	}
	return n
}

func (m *RegisterReq) Size() (n int) {
	var l int
	_ = l
	if m.Rtype != 0 {
		n += 1 + sovPassport(uint64(m.Rtype))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Major)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Idcard)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Origin)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Class)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Admissontime)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.College)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Course)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	return n
}

func (m *LoginReq) Size() (n int) {
	var l int
	_ = l
	if m.Ltype != 0 {
		n += 1 + sovPassport(uint64(m.Ltype))
	}
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	return n
}

func (m *ChangePasswordReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovPassport(uint64(l))
	}
	return n
}

func (m *IndentifyReply) Size() (n int) {
	var l int
	_ = l
	if m.Ltype != 0 {
		n += 1 + sovPassport(uint64(m.Ltype))
	}
	return n
}

func sovPassport(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPassport(x uint64) (n int) {
	return sovPassport(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SessionTokenReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPassport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SessionTokenReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SessionTokenReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stoken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stoken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPassport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPassport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PassportUserReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPassport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PassportUserReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PassportUserReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.User == nil {
				m.User = &api1.UserReply{}
			}
			if err := m.User.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expires", wireType)
			}
			m.Expires = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expires |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPassport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPassport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPassport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rtype", wireType)
			}
			m.Rtype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rtype |= (RegisterReq_RegisterType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Major", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Major = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Idcard", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Idcard = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Origin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Origin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Class", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Class = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admissontime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admissontime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field College", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.College = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Course", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Course = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPassport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPassport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPassport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltype", wireType)
			}
			m.Ltype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ltype |= (LoginReq_LoginType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPassport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPassport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChangePasswordReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPassport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChangePasswordReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChangePasswordReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassport
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPassport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPassport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndentifyReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPassport
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndentifyReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndentifyReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltype", wireType)
			}
			m.Ltype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ltype |= (Indentify(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPassport(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPassport
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPassport(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPassport
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPassport
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPassport
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPassport
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPassport(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPassport = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPassport   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("api/passport.proto", fileDescriptorPassport) }

var fileDescriptorPassport = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc7, 0xeb, 0x7c, 0xe7, 0x24, 0x4d, 0xdd, 0xe9, 0xb2, 0x6b, 0x45, 0x22, 0x59, 0x0d, 0x12,
	0x5a, 0x10, 0xc4, 0x50, 0x44, 0x91, 0xd8, 0x0b, 0xb4, 0x4d, 0x83, 0x8a, 0x8a, 0xda, 0x6a, 0x92,
	0x5e, 0x70, 0x85, 0x1c, 0x7b, 0xea, 0x0e, 0x89, 0x3d, 0xae, 0xc7, 0xa1, 0xe4, 0x45, 0x10, 0x8f,
	0xc4, 0x0d, 0x12, 0x4f, 0x10, 0xa1, 0xf2, 0x06, 0xb9, 0xe1, 0x12, 0x34, 0x33, 0x76, 0x70, 0x5c,
	0x81, 0x5a, 0x6d, 0x6e, 0x32, 0xe7, 0xfc, 0x7f, 0xe7, 0xcc, 0xcc, 0x99, 0xa3, 0x63, 0x40, 0x4e,
	0xc4, 0xec, 0xc8, 0x11, 0x22, 0xe2, 0x71, 0x32, 0x88, 0x62, 0x9e, 0x70, 0x54, 0x76, 0x22, 0xd6,
	0xfd, 0xd8, 0x67, 0xc9, 0xcd, 0x62, 0x3a, 0x70, 0x79, 0x60, 0xfb, 0xdc, 0xe7, 0xb6, 0xd2, 0xa6,
	0x8b, 0x6b, 0x65, 0x29, 0x43, 0xad, 0x74, 0x4c, 0x77, 0x38, 0x0b, 0xf9, 0xdd, 0x9c, 0x7a, 0x3e,
	0x0d, 0x9c, 0xe8, 0xfb, 0xa9, 0xe3, 0xce, 0x68, 0xe8, 0xd9, 0x01, 0x73, 0x63, 0x2e, 0x68, 0xfc,
	0x23, 0x73, 0xa9, 0xb0, 0xf3, 0x88, 0xbd, 0x10, 0x34, 0xb6, 0xe5, 0xe6, 0x72, 0xa1, 0x93, 0xe0,
	0xd7, 0xb0, 0x37, 0xa6, 0x42, 0x30, 0x1e, 0x4e, 0xf8, 0x8c, 0x86, 0x84, 0xde, 0x22, 0x13, 0xca,
	0x0b, 0xe6, 0x59, 0xc6, 0x4b, 0xe3, 0x55, 0x93, 0xc8, 0x25, 0x7a, 0x0e, 0x35, 0x91, 0x48, 0xd9,
	0x2a, 0x29, 0x67, 0x6a, 0x61, 0x1f, 0xf6, 0x2f, 0xd3, 0x7b, 0x5c, 0x09, 0x1a, 0x13, 0x1a, 0xcd,
	0x97, 0x08, 0x43, 0x45, 0xe6, 0x57, 0xf1, 0xad, 0xc3, 0xce, 0xc0, 0x89, 0xd8, 0x60, 0xa3, 0x12,
	0xa5, 0xa1, 0x67, 0x50, 0xcd, 0xe7, 0xd3, 0x06, 0xb2, 0xa0, 0x4e, 0x7f, 0x8a, 0x58, 0x4c, 0x85,
	0x55, 0x7e, 0x69, 0xbc, 0x2a, 0x93, 0xcc, 0xc4, 0xbf, 0x55, 0xa0, 0x45, 0xa8, 0xcf, 0x44, 0x22,
	0xf3, 0xdc, 0xa2, 0x11, 0x54, 0xe3, 0x64, 0x19, 0x51, 0xb5, 0x49, 0xe7, 0xf0, 0x5d, 0xb5, 0x49,
	0x0e, 0xd8, 0xac, 0x27, 0xcb, 0x88, 0x1e, 0x9b, 0xeb, 0x55, 0xbf, 0x7d, 0xcd, 0xe3, 0xe0, 0x4b,
	0xac, 0xa2, 0x30, 0xd1, 0xd1, 0xe8, 0x3d, 0xa8, 0x84, 0x4e, 0x40, 0xf5, 0x29, 0x8e, 0xf7, 0xd6,
	0xab, 0x7e, 0x4b, 0x63, 0xd2, 0x8b, 0x89, 0x12, 0xd1, 0xfb, 0x50, 0x0d, 0x9c, 0x1f, 0x78, 0xac,
	0xce, 0xd4, 0xcc, 0x27, 0x53, 0x6e, 0x4c, 0xb4, 0x8c, 0x3e, 0x80, 0x1a, 0xf3, 0x5c, 0x27, 0xf6,
	0xac, 0x8a, 0x02, 0xf7, 0xd7, 0xab, 0xfe, 0xae, 0x06, 0xb5, 0x1f, 0x93, 0x14, 0x90, 0x28, 0x8f,
	0x99, 0xcf, 0x42, 0xab, 0x5a, 0x44, 0xb5, 0x1f, 0x93, 0x14, 0x90, 0xbb, 0xbb, 0x73, 0x47, 0x08,
	0xab, 0x56, 0xdc, 0x5d, 0xb9, 0x31, 0xd1, 0x32, 0x7a, 0x0d, 0x6d, 0xc7, 0x0b, 0x98, 0x10, 0x3c,
	0x4c, 0x58, 0x40, 0xad, 0xba, 0xc2, 0x5f, 0xac, 0x57, 0xfd, 0x03, 0x8d, 0xe7, 0x55, 0x4c, 0xb6,
	0x60, 0xf4, 0x11, 0xd4, 0x1d, 0xd7, 0xe5, 0x8b, 0x30, 0xb1, 0x1a, 0x2a, 0x0e, 0xad, 0x57, 0xfd,
	0x4e, 0x1a, 0xa7, 0x05, 0x4c, 0x32, 0x04, 0xd9, 0xd0, 0x90, 0xdd, 0x7b, 0xc7, 0x63, 0xcf, 0x6a,
	0x2a, 0xfc, 0x60, 0xbd, 0xea, 0xef, 0x69, 0x3c, 0x53, 0x30, 0xd9, 0x40, 0x32, 0xbd, 0xcb, 0xe7,
	0x73, 0xea, 0x53, 0x0b, 0x8a, 0xe9, 0x53, 0x01, 0x93, 0x0c, 0x91, 0xc5, 0x71, 0xf9, 0x22, 0x16,
	0xd4, 0x6a, 0x15, 0x8b, 0xa3, 0xfd, 0x98, 0xa4, 0x00, 0xfe, 0x02, 0xda, 0xf9, 0x87, 0x46, 0x2d,
	0xa8, 0x8f, 0x27, 0x57, 0x27, 0xa3, 0xf3, 0x89, 0xb9, 0x23, 0x8d, 0xc9, 0xe8, 0xcd, 0xf0, 0x74,
	0x44, 0x4c, 0x03, 0xed, 0x42, 0x73, 0x3c, 0x1a, 0x92, 0xd1, 0xe4, 0x0d, 0xf9, 0xce, 0x2c, 0xe1,
	0xbf, 0x0c, 0x68, 0x7c, 0xcb, 0x7d, 0xa6, 0xfa, 0xfd, 0x2b, 0xa8, 0xce, 0x73, 0xcd, 0xf4, 0x42,
	0x35, 0x53, 0xa6, 0xea, 0x45, 0xb1, 0x8d, 0xe6, 0x69, 0x1b, 0xa9, 0xff, 0x7c, 0xf9, 0x4a, 0x4f,
	0x2b, 0x5f, 0xf9, 0x11, 0xe5, 0xc3, 0x67, 0xd0, 0xdc, 0x1c, 0xe2, 0xd1, 0x57, 0x44, 0xef, 0x40,
	0xe3, 0xfc, 0x62, 0xf2, 0xf5, 0xc5, 0xd5, 0xf9, 0x89, 0xf9, 0x77, 0xf6, 0x33, 0x70, 0x0c, 0xfb,
	0xc3, 0x1b, 0x27, 0xf4, 0xe9, 0x65, 0x9a, 0x5e, 0x56, 0x20, 0x77, 0x01, 0xe3, 0x69, 0x17, 0x28,
	0x3d, 0xe6, 0x02, 0xa7, 0xd0, 0xf9, 0x26, 0xf4, 0x68, 0x98, 0xb0, 0xeb, 0xa5, 0x9e, 0x11, 0x47,
	0xdb, 0x25, 0xd7, 0x43, 0x62, 0xc3, 0xfc, 0x67, 0xa5, 0x3f, 0x3c, 0x83, 0xe6, 0x86, 0x7a, 0xdb,
	0x52, 0x1c, 0xfe, 0x5c, 0x82, 0x46, 0x36, 0xbe, 0xd0, 0x11, 0x34, 0xb2, 0x56, 0x42, 0x66, 0x71,
	0x9c, 0x74, 0x9f, 0x2b, 0xcf, 0x83, 0x59, 0x87, 0x77, 0xd0, 0x27, 0x50, 0x55, 0x8f, 0x83, 0x76,
	0xb7, 0xda, 0xe6, 0x7f, 0x22, 0x3e, 0x85, 0xd6, 0xf0, 0x86, 0xba, 0xb3, 0xb1, 0x1a, 0xb8, 0xe8,
	0x99, 0x02, 0x0b, 0x33, 0xb8, 0x0b, 0xca, 0x3b, 0x0a, 0xa2, 0x44, 0x86, 0x1c, 0x41, 0x67, 0xfb,
	0xd1, 0x90, 0x4e, 0xff, 0xe0, 0x25, 0x0b, 0x71, 0x9f, 0xcb, 0x38, 0xea, 0xce, 0xfe, 0xad, 0x59,
	0x3b, 0x37, 0x8e, 0x6f, 0xbb, 0x07, 0xdb, 0x75, 0x4f, 0x4f, 0x78, 0x6c, 0xfe, 0x7a, 0xdf, 0x33,
	0x7e, 0xbf, 0xef, 0x19, 0x7f, 0xdc, 0xf7, 0x8c, 0x5f, 0xfe, 0xec, 0xed, 0x4c, 0x6b, 0xea, 0x63,
	0xf1, 0xd9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x85, 0x56, 0x47, 0x10, 0xbb, 0x06, 0x00, 0x00,
}
