// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/class.proto

/*
	Package api is a generated protocol buffer package.

	It is generated from these files:
		api/class.proto

	It has these top-level messages:
		ClassReq
		ClassReply
		UserClassReply
		CreateClassReq
		JoinClassReq
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "knowledgemap_backend/microservices/knowledgemap/user/api"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClassReq struct {
	Classid string `protobuf:"bytes,1,opt,name=classid,proto3" json:"classid"`
}

func (m *ClassReq) Reset()                    { *m = ClassReq{} }
func (m *ClassReq) String() string            { return proto.CompactTextString(m) }
func (*ClassReq) ProtoMessage()               {}
func (*ClassReq) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{0} }

func (m *ClassReq) GetClassid() string {
	if m != nil {
		return m.Classid
	}
	return ""
}

type ClassReply struct {
	Classid     string `protobuf:"bytes,1,opt,name=classid,proto3" json:"classid,omitempty" bson:"_id",form:"_id"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Major       string `protobuf:"bytes,3,opt,name=major,proto3" json:"major,omitempty"`
	College     string `protobuf:"bytes,4,opt,name=college,proto3" json:"college,omitempty"`
	Teachername string `protobuf:"bytes,5,opt,name=teachername,proto3" json:"teachername,omitempty"`
	CreateTime  int64  `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Number      string `protobuf:"bytes,7,opt,name=Number,proto3" json:"Number,omitempty"`
}

func (m *ClassReply) Reset()                    { *m = ClassReply{} }
func (m *ClassReply) String() string            { return proto.CompactTextString(m) }
func (*ClassReply) ProtoMessage()               {}
func (*ClassReply) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{1} }

func (m *ClassReply) GetClassid() string {
	if m != nil {
		return m.Classid
	}
	return ""
}

func (m *ClassReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClassReply) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *ClassReply) GetCollege() string {
	if m != nil {
		return m.College
	}
	return ""
}

func (m *ClassReply) GetTeachername() string {
	if m != nil {
		return m.Teachername
	}
	return ""
}

func (m *ClassReply) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ClassReply) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type UserClassReply struct {
	Classes []*ClassReply `protobuf:"bytes,1,rep,name=classes" json:"classes,omitempty"`
}

func (m *UserClassReply) Reset()                    { *m = UserClassReply{} }
func (m *UserClassReply) String() string            { return proto.CompactTextString(m) }
func (*UserClassReply) ProtoMessage()               {}
func (*UserClassReply) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{2} }

func (m *UserClassReply) GetClasses() []*ClassReply {
	if m != nil {
		return m.Classes
	}
	return nil
}

type CreateClassReq struct {
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"classid"`
	Major       string `protobuf:"bytes,2,opt,name=major,proto3" json:"major,omitempty"`
	College     string `protobuf:"bytes,3,opt,name=college,proto3" json:"college,omitempty"`
	Teachername string `protobuf:"bytes,4,opt,name=teachername,proto3" json:"teachername,omitempty"`
}

func (m *CreateClassReq) Reset()                    { *m = CreateClassReq{} }
func (m *CreateClassReq) String() string            { return proto.CompactTextString(m) }
func (*CreateClassReq) ProtoMessage()               {}
func (*CreateClassReq) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{3} }

func (m *CreateClassReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateClassReq) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *CreateClassReq) GetCollege() string {
	if m != nil {
		return m.College
	}
	return ""
}

func (m *CreateClassReq) GetTeachername() string {
	if m != nil {
		return m.Teachername
	}
	return ""
}

type JoinClassReq struct {
	Userid  string `protobuf:"bytes,1,opt,name=userid,proto3" json:"uid"`
	Classid string `protobuf:"bytes,2,opt,name=classid,proto3" json:"classid,omitempty"`
}

func (m *JoinClassReq) Reset()                    { *m = JoinClassReq{} }
func (m *JoinClassReq) String() string            { return proto.CompactTextString(m) }
func (*JoinClassReq) ProtoMessage()               {}
func (*JoinClassReq) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{4} }

func (m *JoinClassReq) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *JoinClassReq) GetClassid() string {
	if m != nil {
		return m.Classid
	}
	return ""
}

func init() {
	proto.RegisterType((*ClassReq)(nil), "api.ClassReq")
	proto.RegisterType((*ClassReply)(nil), "api.ClassReply")
	proto.RegisterType((*UserClassReply)(nil), "api.UserClassReply")
	proto.RegisterType((*CreateClassReq)(nil), "api.CreateClassReq")
	proto.RegisterType((*JoinClassReq)(nil), "api.JoinClassReq")
}
func (m *ClassReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClassReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Classid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Classid)))
		i += copy(dAtA[i:], m.Classid)
	}
	return i, nil
}

func (m *ClassReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClassReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Classid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Classid)))
		i += copy(dAtA[i:], m.Classid)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Major) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Major)))
		i += copy(dAtA[i:], m.Major)
	}
	if len(m.College) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.College)))
		i += copy(dAtA[i:], m.College)
	}
	if len(m.Teachername) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Teachername)))
		i += copy(dAtA[i:], m.Teachername)
	}
	if m.CreateTime != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintClass(dAtA, i, uint64(m.CreateTime))
	}
	if len(m.Number) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Number)))
		i += copy(dAtA[i:], m.Number)
	}
	return i, nil
}

func (m *UserClassReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserClassReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Classes) > 0 {
		for _, msg := range m.Classes {
			dAtA[i] = 0xa
			i++
			i = encodeVarintClass(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *CreateClassReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateClassReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Major) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Major)))
		i += copy(dAtA[i:], m.Major)
	}
	if len(m.College) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.College)))
		i += copy(dAtA[i:], m.College)
	}
	if len(m.Teachername) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Teachername)))
		i += copy(dAtA[i:], m.Teachername)
	}
	return i, nil
}

func (m *JoinClassReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *JoinClassReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Userid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Userid)))
		i += copy(dAtA[i:], m.Userid)
	}
	if len(m.Classid) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Classid)))
		i += copy(dAtA[i:], m.Classid)
	}
	return i, nil
}

func encodeVarintClass(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ClassReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Classid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func (m *ClassReply) Size() (n int) {
	var l int
	_ = l
	l = len(m.Classid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Major)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.College)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Teachername)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	if m.CreateTime != 0 {
		n += 1 + sovClass(uint64(m.CreateTime))
	}
	l = len(m.Number)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func (m *UserClassReply) Size() (n int) {
	var l int
	_ = l
	if len(m.Classes) > 0 {
		for _, e := range m.Classes {
			l = e.Size()
			n += 1 + l + sovClass(uint64(l))
		}
	}
	return n
}

func (m *CreateClassReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Major)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.College)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Teachername)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func (m *JoinClassReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Userid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Classid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func sovClass(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozClass(x uint64) (n int) {
	return sovClass(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClassReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClassReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClassReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClassReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClassReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClassReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Major", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Major = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field College", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.College = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Teachername", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Teachername = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTime", wireType)
			}
			m.CreateTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreateTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Number = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserClassReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserClassReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserClassReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classes = append(m.Classes, &ClassReply{})
			if err := m.Classes[len(m.Classes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateClassReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateClassReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateClassReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Major", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Major = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field College", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.College = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Teachername", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Teachername = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *JoinClassReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: JoinClassReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: JoinClassReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Userid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Userid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClass(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClass
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClass
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClass
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthClass
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowClass
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipClass(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthClass = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClass   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("api/class.proto", fileDescriptorClass) }

var fileDescriptorClass = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0xc6, 0xf9, 0x20, 0x93, 0x7e, 0xc0, 0xf2, 0x21, 0x93, 0x83, 0x13, 0x59, 0x42, 0x0a,
	0x12, 0x8d, 0x45, 0x4b, 0x2f, 0x70, 0x6b, 0x4e, 0xe5, 0xc0, 0xc1, 0x82, 0x73, 0xb5, 0xb6, 0x27,
	0xee, 0x52, 0xdb, 0x6b, 0xd6, 0x31, 0x88, 0x33, 0x7f, 0x82, 0x9f, 0xc4, 0x91, 0x33, 0x87, 0x80,
	0xc2, 0xad, 0x47, 0x7e, 0x01, 0xf2, 0xd8, 0x31, 0x6e, 0x68, 0x7b, 0x9b, 0xf7, 0x66, 0x67, 0xde,
	0xbc, 0x19, 0x2d, 0xec, 0x8b, 0x54, 0x3a, 0x7e, 0x24, 0xb2, 0x6c, 0x96, 0x6a, 0xb5, 0x54, 0xdc,
	0x10, 0xa9, 0x1c, 0x1d, 0x84, 0x72, 0x79, 0x9e, 0x7b, 0x33, 0x5f, 0xc5, 0x4e, 0xa8, 0x42, 0xe5,
	0x50, 0xce, 0xcb, 0x17, 0x84, 0x08, 0x50, 0x54, 0xd6, 0x8c, 0xe6, 0x17, 0x89, 0xfa, 0x14, 0x61,
	0x10, 0x62, 0x2c, 0xd2, 0x33, 0x4f, 0xf8, 0x17, 0x98, 0x04, 0x4e, 0x2c, 0x7d, 0xad, 0x32, 0xd4,
	0x1f, 0xa5, 0x8f, 0x99, 0xd3, 0x7c, 0xe2, 0xe4, 0x19, 0x6a, 0xa7, 0x50, 0x2e, 0x82, 0xb2, 0x89,
	0xfd, 0x1c, 0xee, 0xcc, 0x8b, 0x39, 0x5c, 0xfc, 0xc0, 0x9f, 0x40, 0x9f, 0x66, 0x92, 0x81, 0xc9,
	0x26, 0x6c, 0x3a, 0x38, 0x19, 0x5e, 0xae, 0xc6, 0x1b, 0xca, 0xdd, 0x04, 0xf6, 0x4f, 0x06, 0x50,
	0xd5, 0xa4, 0xd1, 0x67, 0x7e, 0xb4, 0x5d, 0xf5, 0xf8, 0xcf, 0x6a, 0xfc, 0xd0, 0xcb, 0x54, 0xf2,
	0xd2, 0x3e, 0x93, 0x81, 0xfd, 0x6c, 0xa1, 0x74, 0x5c, 0x86, 0x75, 0x0f, 0xce, 0xa1, 0x93, 0x88,
	0x18, 0xcd, 0x76, 0x51, 0xe1, 0x52, 0xcc, 0x1f, 0x40, 0x37, 0x16, 0xef, 0x95, 0x36, 0x0d, 0x22,
	0x4b, 0xc0, 0x4d, 0xe8, 0xfb, 0x2a, 0x8a, 0x30, 0x44, 0xb3, 0x43, 0xfc, 0x06, 0xf2, 0x09, 0x0c,
	0x97, 0x28, 0xfc, 0x73, 0xd4, 0xd4, 0xaa, 0x4b, 0xd9, 0x26, 0xc5, 0x2d, 0x80, 0xb9, 0x46, 0xb1,
	0xc4, 0xb7, 0x32, 0x46, 0xb3, 0x37, 0x61, 0x53, 0xc3, 0x6d, 0x30, 0xfc, 0x11, 0xf4, 0xde, 0xe4,
	0xb1, 0x87, 0xda, 0xec, 0x53, 0x71, 0x85, 0xec, 0x57, 0xb0, 0xf7, 0x2e, 0x43, 0xdd, 0x30, 0xf9,
	0xb4, 0x32, 0x89, 0x99, 0xc9, 0x26, 0xc6, 0x74, 0x78, 0xb8, 0x3f, 0x13, 0xa9, 0x9c, 0xfd, 0x7b,
	0xe1, 0x6e, 0xf2, 0xf6, 0x17, 0x06, 0x7b, 0xa5, 0x46, 0xbd, 0xd8, 0x71, 0xe5, 0xf6, 0x9a, 0xad,
	0x6e, 0x59, 0x6f, 0xdf, 0x60, 0xdd, 0xb8, 0xd5, 0x7a, 0xe7, 0x3f, 0xeb, 0xf6, 0x29, 0xec, 0xbc,
	0x56, 0x32, 0x69, 0x8c, 0xd0, 0x2b, 0xae, 0x5e, 0x1f, 0xa9, 0x7f, 0xb9, 0x1a, 0x1b, 0xb9, 0x0c,
	0xdc, 0x8a, 0x26, 0xb1, 0xea, 0x8c, 0xed, 0x4a, 0xac, 0x84, 0x87, 0x3f, 0x18, 0x74, 0xa9, 0x0f,
	0x3f, 0x86, 0x61, 0xc3, 0x19, 0xbf, 0x5f, 0xee, 0xe0, 0x8a, 0xd7, 0xd1, 0xf6, 0x62, 0xec, 0x16,
	0x3f, 0x80, 0x01, 0xe1, 0xd3, 0x64, 0xa1, 0xf8, 0x6e, 0x33, 0x7f, 0xed, 0xf3, 0x63, 0x18, 0xd4,
	0xa3, 0xf3, 0x7b, 0x94, 0x6f, 0x5a, 0x19, 0x95, 0xb2, 0x57, 0x0f, 0x64, 0xb7, 0xf8, 0x0b, 0xd8,
	0xad, 0x39, 0x52, 0xda, 0xa9, 0xdf, 0xdd, 0x5c, 0x75, 0x72, 0xf7, 0xdb, 0xda, 0x62, 0xdf, 0xd7,
	0x16, 0xfb, 0xb5, 0xb6, 0xd8, 0xd7, 0xdf, 0x56, 0xcb, 0xeb, 0xd1, 0xc7, 0x38, 0xfa, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x86, 0x61, 0x40, 0x01, 0xa4, 0x03, 0x00, 0x00,
}
