// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/class.proto

/*
	Package api is a generated protocol buffer package.

	It is generated from these files:
		api/class.proto

	It has these top-level messages:
		ClassReq
		ClassReply
		UserClassReply
		CreateClassReq
		JoinClassReq
		InvitationReq
		QueryClassUserInfoReply
		SearchClassesInfoReq
		SearchClassesInfoReply
		QueryFormListReply
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "knowledgemap_backend/microservices/knowledgemap/user/api"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClassReq struct {
	Classid string `protobuf:"bytes,1,opt,name=classid,proto3" json:"classid,omitempty" form:"classid"`
}

func (m *ClassReq) Reset()                    { *m = ClassReq{} }
func (m *ClassReq) String() string            { return proto.CompactTextString(m) }
func (*ClassReq) ProtoMessage()               {}
func (*ClassReq) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{0} }

func (m *ClassReq) GetClassid() string {
	if m != nil {
		return m.Classid
	}
	return ""
}

type ClassReply struct {
	Classid      string `protobuf:"bytes,1,opt,name=classid,proto3" json:"classid,omitempty" bson:"_id",form:"_id"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject      string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Course       string `protobuf:"bytes,4,opt,name=course,proto3" json:"course,omitempty"`
	College      string `protobuf:"bytes,5,opt,name=college,proto3" json:"college,omitempty"`
	Teachername  string `protobuf:"bytes,6,opt,name=teachername,proto3" json:"teachername,omitempty"`
	Createtime   int64  `protobuf:"varint,7,opt,name=createtime,proto3" json:"createtime,omitempty"`
	Number       string `protobuf:"bytes,8,opt,name=number,proto3" json:"number,omitempty"`
	Introduction string `protobuf:"bytes,9,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Teacherid    string `protobuf:"bytes,10,opt,name=teacherid,proto3" json:"teacherid,omitempty"`
	Inclass      bool   `protobuf:"varint,11,opt,name=inclass,proto3" json:"inclass,omitempty"`
}

func (m *ClassReply) Reset()                    { *m = ClassReply{} }
func (m *ClassReply) String() string            { return proto.CompactTextString(m) }
func (*ClassReply) ProtoMessage()               {}
func (*ClassReply) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{1} }

func (m *ClassReply) GetClassid() string {
	if m != nil {
		return m.Classid
	}
	return ""
}

func (m *ClassReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClassReply) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ClassReply) GetCourse() string {
	if m != nil {
		return m.Course
	}
	return ""
}

func (m *ClassReply) GetCollege() string {
	if m != nil {
		return m.College
	}
	return ""
}

func (m *ClassReply) GetTeachername() string {
	if m != nil {
		return m.Teachername
	}
	return ""
}

func (m *ClassReply) GetCreatetime() int64 {
	if m != nil {
		return m.Createtime
	}
	return 0
}

func (m *ClassReply) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *ClassReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *ClassReply) GetTeacherid() string {
	if m != nil {
		return m.Teacherid
	}
	return ""
}

func (m *ClassReply) GetInclass() bool {
	if m != nil {
		return m.Inclass
	}
	return false
}

type UserClassReply struct {
	Classes []*ClassReply `protobuf:"bytes,1,rep,name=classes" json:"classes,omitempty"`
}

func (m *UserClassReply) Reset()                    { *m = UserClassReply{} }
func (m *UserClassReply) String() string            { return proto.CompactTextString(m) }
func (*UserClassReply) ProtoMessage()               {}
func (*UserClassReply) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{2} }

func (m *UserClassReply) GetClasses() []*ClassReply {
	if m != nil {
		return m.Classes
	}
	return nil
}

type CreateClassReq struct {
	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" form:"name"`
	Subject      string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty" form:"subject"`
	Course       string `protobuf:"bytes,3,opt,name=course,proto3" json:"course,omitempty" form:"course"`
	College      string `protobuf:"bytes,4,opt,name=college,proto3" json:"college,omitempty" form:"college"`
	Teachername  string `protobuf:"bytes,5,opt,name=teachername,proto3" json:"teachername,omitempty" form:"teachername"`
	Teacherid    string `protobuf:"bytes,6,opt,name=teacherid,proto3" json:"teacherid,omitempty" form:"teacherid"`
	Introduction string `protobuf:"bytes,7,opt,name=introduction,proto3" json:"introduction,omitempty" form:"introduction"`
}

func (m *CreateClassReq) Reset()                    { *m = CreateClassReq{} }
func (m *CreateClassReq) String() string            { return proto.CompactTextString(m) }
func (*CreateClassReq) ProtoMessage()               {}
func (*CreateClassReq) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{3} }

func (m *CreateClassReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateClassReq) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CreateClassReq) GetCourse() string {
	if m != nil {
		return m.Course
	}
	return ""
}

func (m *CreateClassReq) GetCollege() string {
	if m != nil {
		return m.College
	}
	return ""
}

func (m *CreateClassReq) GetTeachername() string {
	if m != nil {
		return m.Teachername
	}
	return ""
}

func (m *CreateClassReq) GetTeacherid() string {
	if m != nil {
		return m.Teacherid
	}
	return ""
}

func (m *CreateClassReq) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

type JoinClassReq struct {
	Userid    string `protobuf:"bytes,1,opt,name=userid,proto3" json:"uid" form:"userid"`
	Classid   string `protobuf:"bytes,2,opt,name=classid,proto3" json:"classid,omitempty" form:"classid"`
	Username  string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty" form:"username"`
	Indentify string `protobuf:"bytes,4,opt,name=indentify,proto3" json:"indentify,omitempty" form:"indentify"`
}

func (m *JoinClassReq) Reset()                    { *m = JoinClassReq{} }
func (m *JoinClassReq) String() string            { return proto.CompactTextString(m) }
func (*JoinClassReq) ProtoMessage()               {}
func (*JoinClassReq) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{4} }

func (m *JoinClassReq) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *JoinClassReq) GetClassid() string {
	if m != nil {
		return m.Classid
	}
	return ""
}

func (m *JoinClassReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *JoinClassReq) GetIndentify() string {
	if m != nil {
		return m.Indentify
	}
	return ""
}

type InvitationReq struct {
	Classid       string `protobuf:"bytes,1,opt,name=classid,proto3" json:"classid,omitempty" form:"classid"`
	Invitaioncode string `protobuf:"bytes,2,opt,name=invitaioncode,proto3" json:"invitaioncode,omitempty" form:"invitationcode"`
	Userid        string `protobuf:"bytes,3,opt,name=userid,proto3" json:"userid,omitempty" form:"userid"`
}

func (m *InvitationReq) Reset()                    { *m = InvitationReq{} }
func (m *InvitationReq) String() string            { return proto.CompactTextString(m) }
func (*InvitationReq) ProtoMessage()               {}
func (*InvitationReq) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{5} }

func (m *InvitationReq) GetClassid() string {
	if m != nil {
		return m.Classid
	}
	return ""
}

func (m *InvitationReq) GetInvitaioncode() string {
	if m != nil {
		return m.Invitaioncode
	}
	return ""
}

func (m *InvitationReq) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type QueryClassUserInfoReply struct {
	Classid  string                                 `protobuf:"bytes,1,opt,name=classid,proto3" json:"classid,omitempty"`
	Students []*QueryClassUserInfoReply_StudentInfo `protobuf:"bytes,2,rep,name=students" json:"students,omitempty"`
}

func (m *QueryClassUserInfoReply) Reset()                    { *m = QueryClassUserInfoReply{} }
func (m *QueryClassUserInfoReply) String() string            { return proto.CompactTextString(m) }
func (*QueryClassUserInfoReply) ProtoMessage()               {}
func (*QueryClassUserInfoReply) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{6} }

func (m *QueryClassUserInfoReply) GetClassid() string {
	if m != nil {
		return m.Classid
	}
	return ""
}

func (m *QueryClassUserInfoReply) GetStudents() []*QueryClassUserInfoReply_StudentInfo {
	if m != nil {
		return m.Students
	}
	return nil
}

type QueryClassUserInfoReply_StudentInfo struct {
	Userid   string `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (m *QueryClassUserInfoReply_StudentInfo) Reset()         { *m = QueryClassUserInfoReply_StudentInfo{} }
func (m *QueryClassUserInfoReply_StudentInfo) String() string { return proto.CompactTextString(m) }
func (*QueryClassUserInfoReply_StudentInfo) ProtoMessage()    {}
func (*QueryClassUserInfoReply_StudentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptorClass, []int{6, 0}
}

func (m *QueryClassUserInfoReply_StudentInfo) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *QueryClassUserInfoReply_StudentInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type SearchClassesInfoReq struct {
	Page        int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" form:"page"`
	Course      string `protobuf:"bytes,2,opt,name=course,proto3" json:"course,omitempty" form:"course"`
	Subject     string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty" form:"subject"`
	College     string `protobuf:"bytes,4,opt,name=college,proto3" json:"college,omitempty" form:"college"`
	Teachername string `protobuf:"bytes,5,opt,name=teachername,proto3" json:"teachername,omitempty" form:"teachername"`
	Userid      string `protobuf:"bytes,6,opt,name=userid,proto3" json:"userid,omitempty" form:"userid"`
}

func (m *SearchClassesInfoReq) Reset()                    { *m = SearchClassesInfoReq{} }
func (m *SearchClassesInfoReq) String() string            { return proto.CompactTextString(m) }
func (*SearchClassesInfoReq) ProtoMessage()               {}
func (*SearchClassesInfoReq) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{7} }

func (m *SearchClassesInfoReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchClassesInfoReq) GetCourse() string {
	if m != nil {
		return m.Course
	}
	return ""
}

func (m *SearchClassesInfoReq) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SearchClassesInfoReq) GetCollege() string {
	if m != nil {
		return m.College
	}
	return ""
}

func (m *SearchClassesInfoReq) GetTeachername() string {
	if m != nil {
		return m.Teachername
	}
	return ""
}

func (m *SearchClassesInfoReq) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type SearchClassesInfoReply struct {
	Classes     []*ClassReply `protobuf:"bytes,1,rep,name=classes" json:"classes,omitempty"`
	Currentpage int64         `protobuf:"varint,2,opt,name=currentpage,proto3" json:"currentpage,omitempty" form:"currentpage"`
	Totalpage   int64         `protobuf:"varint,3,opt,name=totalpage,proto3" json:"totalpage,omitempty" form:"totalpage"`
}

func (m *SearchClassesInfoReply) Reset()                    { *m = SearchClassesInfoReply{} }
func (m *SearchClassesInfoReply) String() string            { return proto.CompactTextString(m) }
func (*SearchClassesInfoReply) ProtoMessage()               {}
func (*SearchClassesInfoReply) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{8} }

func (m *SearchClassesInfoReply) GetClasses() []*ClassReply {
	if m != nil {
		return m.Classes
	}
	return nil
}

func (m *SearchClassesInfoReply) GetCurrentpage() int64 {
	if m != nil {
		return m.Currentpage
	}
	return 0
}

func (m *SearchClassesInfoReply) GetTotalpage() int64 {
	if m != nil {
		return m.Totalpage
	}
	return 0
}

type QueryFormListReply struct {
	Colleges []string `protobuf:"bytes,1,rep,name=colleges" json:"colleges,omitempty" form:"colleges"`
	Subjects []string `protobuf:"bytes,2,rep,name=subjects" json:"subjects,omitempty" form:"subjects"`
	Courses  []string `protobuf:"bytes,3,rep,name=courses" json:"courses,omitempty" form:"courses"`
}

func (m *QueryFormListReply) Reset()                    { *m = QueryFormListReply{} }
func (m *QueryFormListReply) String() string            { return proto.CompactTextString(m) }
func (*QueryFormListReply) ProtoMessage()               {}
func (*QueryFormListReply) Descriptor() ([]byte, []int) { return fileDescriptorClass, []int{9} }

func (m *QueryFormListReply) GetColleges() []string {
	if m != nil {
		return m.Colleges
	}
	return nil
}

func (m *QueryFormListReply) GetSubjects() []string {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *QueryFormListReply) GetCourses() []string {
	if m != nil {
		return m.Courses
	}
	return nil
}

func init() {
	proto.RegisterType((*ClassReq)(nil), "api.ClassReq")
	proto.RegisterType((*ClassReply)(nil), "api.ClassReply")
	proto.RegisterType((*UserClassReply)(nil), "api.UserClassReply")
	proto.RegisterType((*CreateClassReq)(nil), "api.CreateClassReq")
	proto.RegisterType((*JoinClassReq)(nil), "api.JoinClassReq")
	proto.RegisterType((*InvitationReq)(nil), "api.InvitationReq")
	proto.RegisterType((*QueryClassUserInfoReply)(nil), "api.QueryClassUserInfoReply")
	proto.RegisterType((*QueryClassUserInfoReply_StudentInfo)(nil), "api.QueryClassUserInfoReply.StudentInfo")
	proto.RegisterType((*SearchClassesInfoReq)(nil), "api.SearchClassesInfoReq")
	proto.RegisterType((*SearchClassesInfoReply)(nil), "api.SearchClassesInfoReply")
	proto.RegisterType((*QueryFormListReply)(nil), "api.QueryFormListReply")
}
func (m *ClassReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClassReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Classid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Classid)))
		i += copy(dAtA[i:], m.Classid)
	}
	return i, nil
}

func (m *ClassReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClassReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Classid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Classid)))
		i += copy(dAtA[i:], m.Classid)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Subject) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Subject)))
		i += copy(dAtA[i:], m.Subject)
	}
	if len(m.Course) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Course)))
		i += copy(dAtA[i:], m.Course)
	}
	if len(m.College) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.College)))
		i += copy(dAtA[i:], m.College)
	}
	if len(m.Teachername) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Teachername)))
		i += copy(dAtA[i:], m.Teachername)
	}
	if m.Createtime != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintClass(dAtA, i, uint64(m.Createtime))
	}
	if len(m.Number) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Number)))
		i += copy(dAtA[i:], m.Number)
	}
	if len(m.Introduction) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Introduction)))
		i += copy(dAtA[i:], m.Introduction)
	}
	if len(m.Teacherid) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Teacherid)))
		i += copy(dAtA[i:], m.Teacherid)
	}
	if m.Inclass {
		dAtA[i] = 0x58
		i++
		if m.Inclass {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *UserClassReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserClassReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Classes) > 0 {
		for _, msg := range m.Classes {
			dAtA[i] = 0xa
			i++
			i = encodeVarintClass(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *CreateClassReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateClassReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Subject) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Subject)))
		i += copy(dAtA[i:], m.Subject)
	}
	if len(m.Course) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Course)))
		i += copy(dAtA[i:], m.Course)
	}
	if len(m.College) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.College)))
		i += copy(dAtA[i:], m.College)
	}
	if len(m.Teachername) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Teachername)))
		i += copy(dAtA[i:], m.Teachername)
	}
	if len(m.Teacherid) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Teacherid)))
		i += copy(dAtA[i:], m.Teacherid)
	}
	if len(m.Introduction) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Introduction)))
		i += copy(dAtA[i:], m.Introduction)
	}
	return i, nil
}

func (m *JoinClassReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *JoinClassReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Userid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Userid)))
		i += copy(dAtA[i:], m.Userid)
	}
	if len(m.Classid) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Classid)))
		i += copy(dAtA[i:], m.Classid)
	}
	if len(m.Username) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Username)))
		i += copy(dAtA[i:], m.Username)
	}
	if len(m.Indentify) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Indentify)))
		i += copy(dAtA[i:], m.Indentify)
	}
	return i, nil
}

func (m *InvitationReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InvitationReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Classid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Classid)))
		i += copy(dAtA[i:], m.Classid)
	}
	if len(m.Invitaioncode) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Invitaioncode)))
		i += copy(dAtA[i:], m.Invitaioncode)
	}
	if len(m.Userid) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Userid)))
		i += copy(dAtA[i:], m.Userid)
	}
	return i, nil
}

func (m *QueryClassUserInfoReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClassUserInfoReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Classid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Classid)))
		i += copy(dAtA[i:], m.Classid)
	}
	if len(m.Students) > 0 {
		for _, msg := range m.Students {
			dAtA[i] = 0x12
			i++
			i = encodeVarintClass(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *QueryClassUserInfoReply_StudentInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClassUserInfoReply_StudentInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Userid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Userid)))
		i += copy(dAtA[i:], m.Userid)
	}
	if len(m.Username) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Username)))
		i += copy(dAtA[i:], m.Username)
	}
	return i, nil
}

func (m *SearchClassesInfoReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SearchClassesInfoReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Page != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintClass(dAtA, i, uint64(m.Page))
	}
	if len(m.Course) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Course)))
		i += copy(dAtA[i:], m.Course)
	}
	if len(m.Subject) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Subject)))
		i += copy(dAtA[i:], m.Subject)
	}
	if len(m.College) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.College)))
		i += copy(dAtA[i:], m.College)
	}
	if len(m.Teachername) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Teachername)))
		i += copy(dAtA[i:], m.Teachername)
	}
	if len(m.Userid) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintClass(dAtA, i, uint64(len(m.Userid)))
		i += copy(dAtA[i:], m.Userid)
	}
	return i, nil
}

func (m *SearchClassesInfoReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SearchClassesInfoReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Classes) > 0 {
		for _, msg := range m.Classes {
			dAtA[i] = 0xa
			i++
			i = encodeVarintClass(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Currentpage != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintClass(dAtA, i, uint64(m.Currentpage))
	}
	if m.Totalpage != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintClass(dAtA, i, uint64(m.Totalpage))
	}
	return i, nil
}

func (m *QueryFormListReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFormListReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Colleges) > 0 {
		for _, s := range m.Colleges {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Subjects) > 0 {
		for _, s := range m.Subjects {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Courses) > 0 {
		for _, s := range m.Courses {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func encodeVarintClass(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ClassReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Classid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func (m *ClassReply) Size() (n int) {
	var l int
	_ = l
	l = len(m.Classid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Course)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.College)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Teachername)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	if m.Createtime != 0 {
		n += 1 + sovClass(uint64(m.Createtime))
	}
	l = len(m.Number)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Introduction)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Teacherid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	if m.Inclass {
		n += 2
	}
	return n
}

func (m *UserClassReply) Size() (n int) {
	var l int
	_ = l
	if len(m.Classes) > 0 {
		for _, e := range m.Classes {
			l = e.Size()
			n += 1 + l + sovClass(uint64(l))
		}
	}
	return n
}

func (m *CreateClassReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Course)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.College)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Teachername)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Teacherid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Introduction)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func (m *JoinClassReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Userid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Classid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Indentify)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func (m *InvitationReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Classid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Invitaioncode)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Userid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func (m *QueryClassUserInfoReply) Size() (n int) {
	var l int
	_ = l
	l = len(m.Classid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	if len(m.Students) > 0 {
		for _, e := range m.Students {
			l = e.Size()
			n += 1 + l + sovClass(uint64(l))
		}
	}
	return n
}

func (m *QueryClassUserInfoReply_StudentInfo) Size() (n int) {
	var l int
	_ = l
	l = len(m.Userid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func (m *SearchClassesInfoReq) Size() (n int) {
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovClass(uint64(m.Page))
	}
	l = len(m.Course)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.College)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Teachername)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	l = len(m.Userid)
	if l > 0 {
		n += 1 + l + sovClass(uint64(l))
	}
	return n
}

func (m *SearchClassesInfoReply) Size() (n int) {
	var l int
	_ = l
	if len(m.Classes) > 0 {
		for _, e := range m.Classes {
			l = e.Size()
			n += 1 + l + sovClass(uint64(l))
		}
	}
	if m.Currentpage != 0 {
		n += 1 + sovClass(uint64(m.Currentpage))
	}
	if m.Totalpage != 0 {
		n += 1 + sovClass(uint64(m.Totalpage))
	}
	return n
}

func (m *QueryFormListReply) Size() (n int) {
	var l int
	_ = l
	if len(m.Colleges) > 0 {
		for _, s := range m.Colleges {
			l = len(s)
			n += 1 + l + sovClass(uint64(l))
		}
	}
	if len(m.Subjects) > 0 {
		for _, s := range m.Subjects {
			l = len(s)
			n += 1 + l + sovClass(uint64(l))
		}
	}
	if len(m.Courses) > 0 {
		for _, s := range m.Courses {
			l = len(s)
			n += 1 + l + sovClass(uint64(l))
		}
	}
	return n
}

func sovClass(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozClass(x uint64) (n int) {
	return sovClass(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClassReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClassReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClassReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClassReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClassReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClassReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Course", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Course = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field College", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.College = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Teachername", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Teachername = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Createtime", wireType)
			}
			m.Createtime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Createtime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Number = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Introduction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Introduction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Teacherid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Teacherid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inclass", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Inclass = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserClassReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserClassReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserClassReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classes = append(m.Classes, &ClassReply{})
			if err := m.Classes[len(m.Classes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateClassReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateClassReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateClassReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Course", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Course = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field College", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.College = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Teachername", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Teachername = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Teacherid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Teacherid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Introduction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Introduction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *JoinClassReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: JoinClassReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: JoinClassReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Userid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Userid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indentify", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Indentify = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InvitationReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InvitationReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InvitationReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invitaioncode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invitaioncode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Userid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Userid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClassUserInfoReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClassUserInfoReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClassUserInfoReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Students", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Students = append(m.Students, &QueryClassUserInfoReply_StudentInfo{})
			if err := m.Students[len(m.Students)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClassUserInfoReply_StudentInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StudentInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StudentInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Userid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Userid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SearchClassesInfoReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SearchClassesInfoReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SearchClassesInfoReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Course", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Course = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field College", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.College = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Teachername", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Teachername = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Userid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Userid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SearchClassesInfoReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SearchClassesInfoReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SearchClassesInfoReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classes = append(m.Classes, &ClassReply{})
			if err := m.Classes[len(m.Classes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currentpage", wireType)
			}
			m.Currentpage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Currentpage |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Totalpage", wireType)
			}
			m.Totalpage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Totalpage |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFormListReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClass
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFormListReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFormListReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Colleges", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Colleges = append(m.Colleges, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subjects", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subjects = append(m.Subjects, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Courses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClass
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClass
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Courses = append(m.Courses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClass(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClass
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClass(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClass
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClass
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClass
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthClass
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowClass
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipClass(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthClass = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClass   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("api/class.proto", fileDescriptorClass) }

var fileDescriptorClass = []byte{
	// 1029 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0xda, 0xa9, 0x63, 0x3f, 0xc7, 0x71, 0x33, 0x29, 0xc9, 0xd6, 0x54, 0xb6, 0x35, 0x5c,
	0x5c, 0x29, 0xb5, 0x21, 0xa1, 0x55, 0xd5, 0x1e, 0x10, 0x36, 0x20, 0x05, 0xc1, 0x81, 0x8d, 0x38,
	0x47, 0xeb, 0xf5, 0xc4, 0x19, 0xea, 0xdd, 0x59, 0xf6, 0x47, 0x51, 0xfe, 0x13, 0xfe, 0x00, 0x24,
	0xc4, 0x91, 0x3b, 0x67, 0xc4, 0x11, 0x89, 0x03, 0xb7, 0x15, 0x0a, 0x07, 0x24, 0x8e, 0xfe, 0x0b,
	0xd0, 0xbc, 0xd9, 0x1f, 0xb3, 0x4e, 0x9a, 0x90, 0x4b, 0x6f, 0x33, 0xf3, 0xbd, 0x37, 0xf3, 0xfc,
	0x7d, 0xef, 0x7b, 0x6b, 0xe8, 0xd8, 0x3e, 0x1f, 0x3b, 0x4b, 0x3b, 0x0c, 0x47, 0x7e, 0x20, 0x22,
	0x41, 0x6a, 0xb6, 0xcf, 0xbb, 0x4f, 0x16, 0x3c, 0x3a, 0x8f, 0x67, 0x23, 0x47, 0xb8, 0xe3, 0x85,
	0x58, 0x88, 0x31, 0x62, 0xb3, 0xf8, 0x0c, 0x77, 0xb8, 0xc1, 0x95, 0xca, 0xe9, 0x4e, 0x5f, 0x79,
	0xe2, 0xbb, 0x25, 0x9b, 0x2f, 0x98, 0x6b, 0xfb, 0xa7, 0x33, 0xdb, 0x79, 0xc5, 0xbc, 0xf9, 0xd8,
	0xe5, 0x4e, 0x20, 0x42, 0x16, 0xbc, 0xe6, 0x0e, 0x0b, 0xc7, 0x7a, 0xc8, 0x38, 0x0e, 0x59, 0x30,
	0x96, 0x2f, 0xcb, 0x85, 0xba, 0x84, 0x3e, 0x87, 0xc6, 0x54, 0xd6, 0x61, 0xb1, 0x6f, 0xc9, 0x01,
	0x6c, 0x62, 0x4d, 0x7c, 0x6e, 0x1a, 0x03, 0x63, 0xd8, 0x9c, 0x90, 0x55, 0xd2, 0xdf, 0x3e, 0x13,
	0x81, 0xfb, 0x82, 0xa6, 0x00, 0xb5, 0xb2, 0x10, 0xfa, 0x67, 0x15, 0x20, 0x4d, 0xf5, 0x97, 0x17,
	0xe4, 0x68, 0x3d, 0xf9, 0xe1, 0x2a, 0xe9, 0xbf, 0x33, 0x0b, 0x85, 0xf7, 0x82, 0x9e, 0xf2, 0x39,
	0x3d, 0x50, 0xf7, 0x9c, 0xea, 0x77, 0x10, 0x02, 0x1b, 0x9e, 0xed, 0x32, 0xb3, 0x2a, 0x33, 0x2c,
	0x5c, 0x13, 0x13, 0x36, 0xc3, 0x78, 0xf6, 0x0d, 0x73, 0x22, 0xb3, 0x86, 0xc7, 0xd9, 0x96, 0xec,
	0x41, 0xdd, 0x11, 0x71, 0x10, 0x32, 0x73, 0x03, 0x81, 0x74, 0x27, 0x33, 0x1c, 0xb1, 0x5c, 0xb2,
	0x05, 0x33, 0xef, 0xa9, 0x8c, 0x74, 0x4b, 0x06, 0xd0, 0x8a, 0x98, 0xed, 0x9c, 0xb3, 0x00, 0x9f,
	0xa9, 0x23, 0xaa, 0x1f, 0x91, 0x1e, 0x80, 0x13, 0x30, 0x3b, 0x62, 0x11, 0x77, 0x99, 0xb9, 0x39,
	0x30, 0x86, 0x35, 0x4b, 0x3b, 0x91, 0x6f, 0x7a, 0xb1, 0x3b, 0x63, 0x81, 0xd9, 0x50, 0x6f, 0xaa,
	0x1d, 0xa1, 0xb0, 0xc5, 0xbd, 0x28, 0x10, 0xf3, 0xd8, 0x89, 0xb8, 0xf0, 0xcc, 0x26, 0xa2, 0xa5,
	0x33, 0xf2, 0x08, 0x9a, 0xe9, 0x53, 0x7c, 0x6e, 0x02, 0x06, 0x14, 0x07, 0xb2, 0x6a, 0xee, 0x21,
	0x11, 0x66, 0x6b, 0x60, 0x0c, 0x1b, 0x56, 0xb6, 0xa5, 0x2f, 0x61, 0xfb, 0xeb, 0x90, 0x05, 0x1a,
	0xb9, 0x8f, 0x53, 0x72, 0x59, 0x68, 0x1a, 0x83, 0xda, 0xb0, 0x75, 0xd8, 0x19, 0xd9, 0x3e, 0x1f,
	0x15, 0x11, 0x56, 0x86, 0xd3, 0x7f, 0xaa, 0xb0, 0x3d, 0xc5, 0xfa, 0x73, 0x5d, 0xdf, 0x4b, 0x59,
	0x56, 0xba, 0x74, 0x56, 0x49, 0xbf, 0xa5, 0xc4, 0x90, 0xa7, 0x34, 0xa5, 0xfd, 0xa0, 0xa0, 0xbd,
	0xba, 0x2e, 0x7e, 0x0a, 0xd0, 0x42, 0x8a, 0xc7, 0xb9, 0x14, 0xa8, 0xd1, 0x64, 0x67, 0x95, 0xf4,
	0xdb, 0x69, 0xa7, 0xe0, 0x39, 0xcd, 0xd5, 0x39, 0x28, 0xd4, 0xd9, 0xb8, 0xd2, 0x55, 0x0a, 0xa0,
	0x85, 0x62, 0xcf, 0xcb, 0x8a, 0xa1, 0x9e, 0x93, 0xbd, 0x55, 0xd2, 0x27, 0x2a, 0x43, 0x03, 0x69,
	0x59, 0xc9, 0x43, 0x9d, 0x6d, 0x54, 0x7a, 0xf2, 0x60, 0x95, 0xf4, 0xef, 0x97, 0xf2, 0x64, 0xf7,
	0x69, 0x1a, 0xbc, 0x5c, 0x53, 0x71, 0x13, 0xd3, 0xf6, 0x57, 0x49, 0x7f, 0x57, 0xa5, 0xe9, 0x28,
	0x2d, 0xcb, 0x4b, 0xff, 0x30, 0x60, 0xeb, 0x73, 0xc1, 0xbd, 0x9c, 0xe7, 0xf7, 0xa1, 0x2e, 0x9d,
	0x95, 0x3b, 0xc0, 0xfc, 0x37, 0xe9, 0xd7, 0x62, 0x3e, 0x2f, 0xb8, 0x51, 0x30, 0xb5, 0xd2, 0x38,
	0xdd, 0x71, 0xd5, 0x5b, 0x1d, 0x47, 0xc6, 0xd0, 0x90, 0x79, 0x48, 0x8c, 0xa2, 0x7d, 0x77, 0x95,
	0xf4, 0x3b, 0xc5, 0xd5, 0x8a, 0x95, 0x3c, 0x48, 0x52, 0xc2, 0xbd, 0x39, 0xf3, 0x22, 0x7e, 0x76,
	0x91, 0x92, 0xaf, 0x51, 0x92, 0x43, 0xd4, 0x2a, 0xc2, 0xe8, 0x4f, 0x06, 0xb4, 0x8f, 0xbd, 0xd7,
	0x3c, 0xb2, 0xe5, 0x8f, 0xbc, 0xf3, 0x58, 0x20, 0x1f, 0x41, 0x9b, 0x63, 0x3a, 0x17, 0x9e, 0x23,
	0xe6, 0xa9, 0xb7, 0xd5, 0x34, 0xc8, 0xde, 0xcd, 0x6e, 0x97, 0x38, 0xb5, 0xca, 0xf1, 0xb2, 0xb5,
	0x52, 0x16, 0xaf, 0xb4, 0xd6, 0x1a, 0x7d, 0xf4, 0x17, 0x03, 0xf6, 0xbf, 0x8a, 0x59, 0x70, 0x81,
	0x12, 0x48, 0xcf, 0x1c, 0x7b, 0x67, 0x42, 0x59, 0xc6, 0x5c, 0xab, 0xba, 0xa8, 0xf0, 0x13, 0x68,
	0x84, 0x51, 0x2c, 0x7f, 0x6f, 0x68, 0x56, 0xd1, 0x4d, 0x43, 0x74, 0xd3, 0x1b, 0x6e, 0x1a, 0x9d,
	0xa8, 0x60, 0x3c, 0xc8, 0x33, 0xbb, 0x1f, 0x43, 0x4b, 0x03, 0xe4, 0x9c, 0xd0, 0xb5, 0xcf, 0x15,
	0xee, 0x6a, 0x9a, 0xa9, 0x29, 0x97, 0xef, 0xe9, 0x8f, 0x55, 0x78, 0x70, 0xc2, 0xec, 0xc0, 0x39,
	0x9f, 0x2a, 0xf3, 0xaa, 0x37, 0xd1, 0xb0, 0xbe, 0xbd, 0x50, 0x86, 0xad, 0xe9, 0x86, 0x95, 0xa7,
	0xd4, 0x42, 0x50, 0xb3, 0x60, 0xf5, 0x7f, 0x58, 0xb0, 0x34, 0x52, 0x6f, 0xf6, 0xf6, 0xdb, 0x32,
	0x6c, 0x21, 0x74, 0xfd, 0x36, 0xa1, 0x7f, 0x36, 0x60, 0xef, 0x1a, 0xa6, 0xee, 0x36, 0x1a, 0x65,
	0xa9, 0x4e, 0x1c, 0x04, 0xcc, 0x8b, 0x90, 0xdd, 0x2a, 0xb2, 0xab, 0x95, 0xaa, 0x81, 0xd4, 0xd2,
	0x43, 0x71, 0xb6, 0x88, 0xc8, 0x5e, 0x62, 0x5e, 0x0d, 0xf3, 0xf4, 0xd9, 0x92, 0x41, 0x72, 0xb6,
	0xe4, 0xeb, 0x1f, 0x0c, 0x20, 0xd8, 0x52, 0x9f, 0x89, 0xc0, 0xfd, 0x82, 0x87, 0x91, 0xaa, 0x77,
	0x0c, 0x8d, 0x94, 0x3a, 0x55, 0x70, 0xc9, 0xc4, 0x19, 0x42, 0xad, 0x3c, 0x48, 0x26, 0xa4, 0xca,
	0xa8, 0x76, 0x2d, 0x25, 0x64, 0x08, 0xb5, 0xf2, 0x20, 0xa5, 0x9f, 0xd4, 0x3d, 0x34, 0x6b, 0x18,
	0x5f, 0xd2, 0x0f, 0x01, 0xd4, 0x0f, 0x57, 0x87, 0xbf, 0x6e, 0xc0, 0x3d, 0x24, 0x8b, 0x3c, 0x85,
	0x96, 0xf6, 0xe1, 0x20, 0xbb, 0x8a, 0xc7, 0xd2, 0xa7, 0xa4, 0xbb, 0x4e, 0x2e, 0xad, 0x90, 0x27,
	0xd0, 0xc4, 0x3d, 0xda, 0xa0, 0xad, 0xe3, 0xd7, 0x86, 0x3f, 0x85, 0x66, 0x3e, 0x34, 0xc9, 0x0e,
	0xe2, 0xfa, 0x10, 0xed, 0xaa, 0x67, 0xcb, 0xdf, 0x3f, 0x5a, 0x21, 0x1f, 0x42, 0x3b, 0x3f, 0xc3,
	0x97, 0xb6, 0xf2, 0xb8, 0x1b, 0xb2, 0xa6, 0xa9, 0x04, 0x25, 0x57, 0xaf, 0x17, 0xf9, 0xe8, 0x26,
	0xf7, 0xd3, 0x0a, 0xf9, 0x12, 0x76, 0xae, 0xf4, 0x1e, 0x79, 0x88, 0x49, 0xd7, 0xb9, 0xb7, 0xfb,
	0xee, 0x9b, 0x20, 0x75, 0xdd, 0x33, 0x68, 0x97, 0xda, 0x82, 0x00, 0xc6, 0x7f, 0xea, 0xfa, 0xd1,
	0x45, 0x77, 0xbf, 0xa8, 0xa5, 0xd4, 0x36, 0xb4, 0x42, 0x8e, 0xa0, 0xa3, 0xc4, 0x38, 0xce, 0xc6,
	0x25, 0x21, 0x18, 0x5d, 0x9a, 0xd6, 0x5d, 0xed, 0x36, 0x5a, 0x21, 0x1f, 0x40, 0xfb, 0x24, 0x12,
	0xfe, 0x5d, 0x52, 0x9e, 0x65, 0xf3, 0x9f, 0x0b, 0x0f, 0x7f, 0xea, 0x75, 0x29, 0x57, 0x85, 0x9d,
	0xdc, 0xff, 0xed, 0xb2, 0x67, 0xfc, 0x7e, 0xd9, 0x33, 0xfe, 0xba, 0xec, 0x19, 0xdf, 0xff, 0xdd,
	0xab, 0xcc, 0xea, 0xf8, 0x17, 0xf3, 0xe8, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82, 0xbc, 0x9b,
	0xb6, 0xee, 0x0a, 0x00, 0x00,
}
